# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: afaura-v <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/23 20:31:24 by afaura-v          #+#    #+#              #
#    Updated: 2019/07/25 21:52:35 by afaura-v         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
FILES = ft_puterror.c main.c

all:
	gcc -Wall -Wextra -Werror $(FILES) -o ft_display_file
clean:
	rm -f ft_display_file
fclean: clean
re: fclean all
